# Generated by Django 5.0.6 on 2024-06-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visit',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
