# Generated by Django 5.0.6 on 2024-06-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_project_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='visit',
        ),
    ]
